### ISSUE TITLE
Liking strange/inapropriate posts

### ISSUE THREAD

**Issue by GaWr26** [breuerfelix/jinsta#10]
Just found "liked posts" feature in the IG App under settings - account - Posts You've liked.

This was before the latest update and unfortunately this does not at all fit my travel keywords...

Haha!

![image](https://user-images.githubusercontent.com/1381617/66947542-5a554400-f053-11e9-8589-28d6eabe8ddf.png)

**Comment by breuerfelix** [comment]
i implemented a black list with sensible defaults :) feel free to open up a pull request or a new issue, if you need more words in the blacklist :D (you can test them with the new advanced option in the readme :))

looking forward to this !
