### ISSUE TITLE
comment liking currently not supported

### ISSUE THREAD

**Issue by enrifer** [breuerfelix/jinsta#15]
The bot started pretty good and liked some photos. After liking 7-10 pictures the following is shown in the session:

comment liking currently not supported
current progress: 190
skip media!

And current progress is still going up.

Hope this helps to improve the code 👍

**Comment by enrifer** [comment]
comment liking currently not supported
current progress: 1030
skip media!

Now it's up to 1030 and not liking anymore

**Comment by breuerfelix** [comment]
this is due to the fact that we didnt implement liking comments for now :)

i could adjusts the values a little bit more so that the feed wont be stuck in comment mode, but there will be a huge refactor soon, so this wont happen again :)

**Comment by breuerfelix** [comment]
/edit

if you want the like rate to be higher now, just set the `nested_feed_chance` to `.0` and it will only stay on the basefeed
