### ISSUE TITLE
story masslooking

### ISSUE THREAD

**Issue by breuerfelix** [breuerfelix/jinsta#34]
could be implemented really easy with our library.

https://github.com/dilame/instagram-private-api/blob/master/examples/user-stories-watching.example.ts

just have a look at this example code

**Comment by halalfood** [comment]
one thing I would add: In the Instagram help documentation, they say you have to watch a story for 3 seconds before it gets marked as seen. Not sure if it applies here but I would at least have delays of 15 seconds between stories since that's the max seconds per story.

**Comment by DrRek** [comment]
https://github.com/breuerfelix/jinsta/pull/56

**Comment by DrRek** [comment]
@halalfood at least from the current implementation of stories view function in instagram-private-api it is possibile to send an array of stories and let him handle it.
I've tested it and at least for now it seems to work well (stories get marked as viewed). If eventually we'll notice some blocks from instagram we'll wrap ipa function with delays and similar to simulate human behavior

**Comment by breuerfelix** [comment]
merged into master :)

**Comment by imkimchi** [comment]
I'm getting `Too many reels requested` error after first try.
I think It should need some delays

https://github.com/breuerfelix/jinsta/issues/65
