### ISSUE TITLE
response from like: [object Object]

### ISSUE THREAD

**Issue by apaticmusic** [breuerfelix/jinsta#36]
...
info:    response from like: [object Object]
...

Is it OK? I think it should be more informative? No?

How can I check who was liked?

**Comment by apaticmusic** [comment]
It would be nice if there will be an information about username whos photo I liked and photo ID or smth.

**Comment by GaWr26** [comment]
@apaticmusic I have the same with the log on like.
For checking which posts were liked I use the IG App.
Go to your profile -> Menu Top right -> Settings ->Account -> Posts You've liked.

I completely agree that it would be great to see the liked Posts somewhere. Maybe the URLs in the log file?

**Comment by micheledellaguardia** [comment]
the same for me:
***
 info: response from like: [object Object]
***

but actually no post has been liked.

**Comment by breuerfelix** [comment]
i think that these posts are ads ... i need to figure out a way to filter them out :)
