### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by micheledellaguardia** [breuerfelix/jinsta#41]
Hi,
today I was running Jinsta, but after some time and no actual like with this info on possible interactions:

info:    like media
info:    response from like: [object Object]

I had this error and jinsta crashed

info:    current progress: 235 / 251
info:    interact with media
info:    like media
(node:3804) UnhandledPromiseRejectionWarning: IgResponseError: POST /api/v1/media/2161027427273349941_7188316441/like/ - 400 Bad Request; Sorry, you cannot like this media
    at Request.handleResponseError (/home/michele/jinsta_data/node_modules/instagram-private-api/dist/core/request.js:102:16)
    at Request.send (/home/michele/jinsta_data/node_modules/instagram-private-api/dist/core/request.js:49:28)
(node:3804) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3804) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by breuerfelix** [comment]
it could be that this media was an ad... i have to filter them out :) i will do that in the new refactoring!
