### ISSUE TITLE
Denser more detailed logging

### ISSUE THREAD

**Issue by HMellor** [breuerfelix/jinsta#42]
Using carriage returns you could condense the logging to take up less vertical space in the console (log files could be more verbose). Also it would be nice to have a running total of progress towards max likes (and maybe other information such as users and image URLs as other people have mentioned). For example:
```
info:    base feed progress: 583 / 598, total liked: 35/100
info:    generate new feed from {user/image}
info:    this feed progress: 0 / 12, total liked: 35/100
```

**Comment by breuerfelix** [comment]
check out the new logging please :) well i forgot to implement the progress but i will do that asap !

**Comment by HMellor** [comment]
Just had a look at the new logging and it is looking good! My only comment would be that a user can't directly do anything with the media ID. I think this link can help you [decode the IDs to URLs](https://carrot.is/coding/instagram-ids).

**Comment by breuerfelix** [comment]
fixed it :) new version will be deployed soon, check it!

**Comment by breuerfelix** [comment]
great idea btw :P
