### ISSUE TITLE
Bot crashes during hashtaglike

### ISSUE THREAD

**Issue by cookie1111** [breuerfelix/jinsta#49]
While liking through a hashtag the bot crashes if a post is deleted. This in turn doesn't correctly close session.json and the bot is unable to start once again unless you delete session.json manually!
Exception:
/insta/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

IgResponseError: POST /api/v1/media/2166213821610818354_333550247/like/ - 400 Bad Request; Sorry, this media has been deleted
    at Request.handleResponseError (/insta/node_modules/instagram-private-api/dist/core/request.js:102:16)
    at Request.send (/nsta/node_modules/instagram-private-api/dist/core/request.js:49:28)
    at <anonymous>

**Comment by DrRek** [comment]
Fix is waiting for review and should be soon merged. Thanks for your time reporting this issue @cookie1111 

https://github.com/breuerfelix/jinsta/pull/53

**Comment by breuerfelix** [comment]
should be fixed now ! (when we release the new version, but its in master already :))
