### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by breuerfelix** [breuerfelix/jinsta#7]
Summarize the current state of discussions on discord

- better logger (winston ?)
- get rid of OOP (more functional)
- dont spend so much time on comments / one profile
- take a hashtag search as basefeed not the timeline
- wrap it as a npm package (cli program)
- change name

**Comment by danniefraim** [comment]
It's good that you summarized what needs to be done, but I really think this should be broken down for the sake of keeping track of what has been done, for managing pull requests, and so on. So most of the points here should be made into their own issues, so someone can actually start working on them. Except perhaps "get rid of OOP" which I think is too broad to be an issue, that needs to be broken down further.

I might start working on a few of these. I've already done a little work on clearer logging, perhaps I'll continue with that. And I would also like to work a bit on the hashtag search function and limiting the interaction depth. My idea of a good bot is that it would go through a couple of searches and work from there, not going too far into profiles and so on. I have an idea in my head here that perhaps we could build a tree of possible actions, then weight the actions based on some criteria, and after that select an action randomly (with consideration to the weighting). So at any given point, there is a certain percentage that the bot will keep scrolling, will go into a profile, will go back and start a new search, and so on, and that those actions also need to be tied to where the bot is currently at, so it mimics the behaviour of a real user.

Also, I would like to start working on some kind of system for the bot to save more state and keep track of what it has and hasn't done, so it doesn't get repetitive (or spammy). Plus, a follow/unfollow function would be really great.

Another thing I'd like to add is a randomized delay between actions, with different intervals for different actions, again, to make the bot less predictable.

If I start working on any of this, I'll create a new issue first so you guys know what's being done and not.

**Comment by breuerfelix** [comment]
i just split this up in different issues now ! this will help alot :)
